/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.dumitru;

import com.dumitru.taskmanager.BaseTaskManager;
import com.dumitru.taskmanager.TaskManager;
import com.dumitru.taskmanager.exception.ProcessLimitExceededException;
import com.dumitru.taskmanager.process.Process;

import static com.dumitru.taskmanager.process.Priority.*;

public class App {

    public static void main(String[] args) {
        runTaskManagerScenarios();
    }

    public static void runTaskManagerScenarios() {
        Process p1 = new Process(HIGH);
        Process p2 = new Process(LOW);
        Process p3 = new Process(MEDIUM);
        Process p4 = new Process(LOW);
        Process p5 = new Process(HIGH);
        Process p6 = new Process(MEDIUM);
        TaskManager taskManager = new BaseTaskManager();
        try {
            taskManager.add(p1);
            taskManager.add(p2);
            taskManager.add(p3);
            taskManager.add(p4);
            taskManager.add(p5);
            taskManager.add(p6);
        } catch (ProcessLimitExceededException e) {
            e.printStackTrace();
        }

        printProcessesDetailsSortedByCreationTime(taskManager);

        taskManager.kill(new Process(HIGH));
        taskManager.kill(p3);
        printProcessesDetailsSortedByCreationTime(taskManager);

        taskManager.killGroup(HIGH);
        printProcessesDetailsSortedByCreationTime(taskManager);

        taskManager.killAll();
        printProcessesDetailsSortedByCreationTime(taskManager);
    }

    private static void printProcessesDetailsSortedByCreationTime(TaskManager taskManager) {
        for (Process p : taskManager.list()) {
            System.out.println(p.toString());
        }
        System.out.println();
    }
}
